spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://192.168.99.100:3306/food
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: test
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.foodmatching.model
  mapper-locations:
    classpath:mybatis/mapper/**/*xml
  
board:
  img:
    path: /Users/shin/Documents/imsiImages
    user:
      path: /Users/shin/Documents/imsiImages/profiles
user:
  target:
    preurl: preURL
