spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://url:3360
    driver-class-name: com.mysql.jdbc.Driver
    username: username
    password: password
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.foodmatching.model
  mapper-locations:
    classpath:mybatis/mapper/**/*xml
  
board:
  img:
    path: imapgePath
    user:
      path: userimagepath
user:
  target:
    preurl: preURL
